///************************************************
/// Generated by: TuyenNT
/// Date: 04/02/2015 03:36:17
/// Goal: Create User Service Class for GD_CHI_TIET_PHIEU_THU
///************************************************
/// <summary>
/// Create User Service Class for GD_CHI_TIET_PHIEU_THU
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US{

public class US_GD_CHI_TIET_PHIEU_THU : US_Object
{
	private const string c_TableName = "GD_CHI_TIET_PHIEU_THU";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_GD_PHIEU_THU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GD_PHIEU_THU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GD_PHIEU_THU"] = value;
		}
	}

	public bool IsID_GD_PHIEU_THUNull()	{
		return pm_objDR.IsNull("ID_GD_PHIEU_THU");
	}

	public void SetID_GD_PHIEU_THUNull() {
		pm_objDR["ID_GD_PHIEU_THU"] = System.Convert.DBNull;
	}

	public decimal dcID_LOP_MON 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOP_MON", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOP_MON"] = value;
		}
	}

	public bool IsID_LOP_MONNull()	{
		return pm_objDR.IsNull("ID_LOP_MON");
	}

	public void SetID_LOP_MONNull() {
		pm_objDR["ID_LOP_MON"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN"] = value;
		}
	}

	public bool IsSO_TIENNull()	{
		return pm_objDR.IsNull("SO_TIEN");
	}

	public void SetSO_TIENNull() {
		pm_objDR["SO_TIEN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_CHI_TIET_PHIEU_THU() 
	{
		pm_objDS = new DS_GD_CHI_TIET_PHIEU_THU();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_CHI_TIET_PHIEU_THU(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_CHI_TIET_PHIEU_THU(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_CHI_TIET_PHIEU_THU();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion

    public void deleteAllFromIDPhieuThu(decimal ip_dc_id_gd_phieu_thu) {
        CStoredProc v_csp = new CStoredProc("pr_del_all_record_ctpt_tu_pt");
        v_csp.addDecimalInputParam("@ip_dc_id_phieu_thu",ip_dc_id_gd_phieu_thu);
        v_csp.ExecuteCommand(this);
    }
}
}
