///************************************************
/// Generated by: TuyenNT
/// Date: 24/01/2015 01:41:34
/// Goal: Create User Service Class for V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS
///************************************************
/// <summary>
/// Create User Service Class for V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US
{

    public class US_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS : US_Object
    {
        private const string c_TableName = "V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS";
        #region "Public Properties"
        public decimal dcID
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID"] = value;
            }
        }

        public bool IsIDNull()
        {
            return pm_objDR.IsNull("ID");
        }

        public void SetIDNull()
        {
            pm_objDR["ID"] = System.Convert.DBNull;
        }

        public string strMA_LOP_MON
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_LOP_MON", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_LOP_MON"] = value;
            }
        }

        public bool IsMA_LOP_MONNull()
        {
            return pm_objDR.IsNull("MA_LOP_MON");
        }

        public void SetMA_LOP_MONNull()
        {
            pm_objDR["MA_LOP_MON"] = System.Convert.DBNull;
        }

        public decimal dcID_HOC_SINH
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_HOC_SINH", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_HOC_SINH"] = value;
            }
        }

        public bool IsID_HOC_SINHNull()
        {
            return pm_objDR.IsNull("ID_HOC_SINH");
        }

        public void SetID_HOC_SINHNull()
        {
            pm_objDR["ID_HOC_SINH"] = System.Convert.DBNull;
        }

        public string strMA_DOI_TUONG
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MA_DOI_TUONG", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MA_DOI_TUONG"] = value;
            }
        }

        public bool IsMA_DOI_TUONGNull()
        {
            return pm_objDR.IsNull("MA_DOI_TUONG");
        }

        public void SetMA_DOI_TUONGNull()
        {
            pm_objDR["MA_DOI_TUONG"] = System.Convert.DBNull;
        }

        public decimal dcID_LOAI_DOI_TUONG
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_DOI_TUONG", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_LOAI_DOI_TUONG"] = value;
            }
        }

        public bool IsID_LOAI_DOI_TUONGNull()
        {
            return pm_objDR.IsNull("ID_LOAI_DOI_TUONG");
        }

        public void SetID_LOAI_DOI_TUONGNull()
        {
            pm_objDR["ID_LOAI_DOI_TUONG"] = System.Convert.DBNull;
        }

        public string strHO
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO"] = value;
            }
        }

        public bool IsHONull()
        {
            return pm_objDR.IsNull("HO");
        }

        public void SetHONull()
        {
            pm_objDR["HO"] = System.Convert.DBNull;
        }

        public string strTEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["TEN"] = value;
            }
        }

        public bool IsTENNull()
        {
            return pm_objDR.IsNull("TEN");
        }

        public void SetTENNull()
        {
            pm_objDR["TEN"] = System.Convert.DBNull;
        }

        public string strHO_TEN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "HO_TEN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["HO_TEN"] = value;
            }
        }

        public bool IsHO_TENNull()
        {
            return pm_objDR.IsNull("HO_TEN");
        }

        public void SetHO_TENNull()
        {
            pm_objDR["HO_TEN"] = System.Convert.DBNull;
        }

        public string strMO_TA
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "MO_TA", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["MO_TA"] = value;
            }
        }

        public bool IsMO_TANull()
        {
            return pm_objDR.IsNull("MO_TA");
        }

        public void SetMO_TANull()
        {
            pm_objDR["MO_TA"] = System.Convert.DBNull;
        }

        public decimal dcDON_GIA_BUOI_HOC
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "DON_GIA_BUOI_HOC", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["DON_GIA_BUOI_HOC"] = value;
            }
        }

        public bool IsDON_GIA_BUOI_HOCNull()
        {
            return pm_objDR.IsNull("DON_GIA_BUOI_HOC");
        }

        public void SetDON_GIA_BUOI_HOCNull()
        {
            pm_objDR["DON_GIA_BUOI_HOC"] = System.Convert.DBNull;
        }

        public decimal dcTIEN_PHAI_THU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TIEN_PHAI_THU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TIEN_PHAI_THU"] = value;
            }
        }

        public bool IsTIEN_PHAI_THUNull()
        {
            return pm_objDR.IsNull("TIEN_PHAI_THU");
        }

        public void SetTIEN_PHAI_THUNull()
        {
            pm_objDR["TIEN_PHAI_THU"] = System.Convert.DBNull;
        }

        public decimal dcTIEN_GIAM_TRU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TIEN_GIAM_TRU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TIEN_GIAM_TRU"] = value;
            }
        }

        public bool IsTIEN_GIAM_TRUNull()
        {
            return pm_objDR.IsNull("TIEN_GIAM_TRU");
        }

        public void SetTIEN_GIAM_TRUNull()
        {
            pm_objDR["TIEN_GIAM_TRU"] = System.Convert.DBNull;
        }

        public decimal dcTIEN_THUC_THU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TIEN_THUC_THU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TIEN_THUC_THU"] = value;
            }
        }

        public bool IsTIEN_THUC_THUNull()
        {
            return pm_objDR.IsNull("TIEN_THUC_THU");
        }

        public void SetTIEN_THUC_THUNull()
        {
            pm_objDR["TIEN_THUC_THU"] = System.Convert.DBNull;
        }

        public decimal dcTIEN_CON_PHAI_THU
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TIEN_CON_PHAI_THU", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TIEN_CON_PHAI_THU"] = value;
            }
        }

        public bool IsTIEN_CON_PHAI_THUNull()
        {
            return pm_objDR.IsNull("TIEN_CON_PHAI_THU");
        }

        public void SetTIEN_CON_PHAI_THUNull()
        {
            pm_objDR["TIEN_CON_PHAI_THU"] = System.Convert.DBNull;
        }

        #endregion
        #region "Init Functions"
        public US_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS()
        {
            pm_objDS = new DS_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS(decimal i_dbID)
        {
            pm_objDS = new DS_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion

        public void FillDataset(DS_V_RPT_420_BC_TAI_CHINH_THEO_LOP_MON_HS iop_ds
                                                            , DateTime ip_dat_dau_thang
                                                            , DateTime ip_dat_cuoi_thang
                                                            , string ip_str_search
                                                            , decimal ip_dc_id_lop_mon
                                                            , decimal ip_dc_id_hoc_sinh)
        {
            CStoredProc v_obj = new CStoredProc("f420_bao_cao_tai_chinh_theo_lop_mon_hs");
            v_obj.addDatetimeInputParam("@ip_dat_dau_thang", ip_dat_dau_thang);
            v_obj.addDatetimeInputParam("@ip_dat_cuoi_thang", ip_dat_cuoi_thang);
            v_obj.addNVarcharInputParam("@ip_str_search", ip_str_search);
            v_obj.addDecimalInputParam("@ip_dc_id_lop_mon", ip_dc_id_lop_mon);
            v_obj.addDecimalInputParam("@ip_dc_id_hoc_sinh", ip_dc_id_hoc_sinh);
            v_obj.fillDataSetByCommand(this, iop_ds);
        }
    }
}
